POST http://localhost:3333/videosPost
Content-Type: application/json

{
    "title": "Video 001",
    "description": "Testando essa bodega",
    "duration": 180
}

###

GET http://localhost:3333/videosGet
